CREATE DATABASE IF NOT EXISTS autoparts;

USE autoparts;

CREATE TABLE IF NOT EXISTS users(
    id int NOT NULL UNIQUE AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS brands(
    id INT NOT NULL UNIQUE AUTO_INCREMENT,
    name VARCHAR(255) UNIQUE NOT NULL,
    code VARCHAR(3) UNIQUE NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS models(
    id INT UNIQUE NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) UNIQUE NOT NULL,
    code VARCHAR(3) UNIQUE NOT NULL,
    brand_code VARCHAR(3),
    PRIMARY KEY (id),
    FOREIGN KEY (brand_code) REFERENCES brands(code)
);

CREATE TABLE IF NOT EXISTS parts(
    id INT UNIQUE NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) UNIQUE NOT NULL,
    code VARCHAR(3) UNIQUE NOT NULL,
    price DECIMAL NOT NULL,
    amount INT NOT NULL,
    model_code VARCHAR(3),
    PRIMARY KEY (id),
    FOREIGN KEY (model_code) REFERENCES models(code)
);